project:
  type: website
  output-dir: _site
metadata-files:
  - course.yml
website:
  title: "Machine Learning for Big Data"
  favicon: assets/favicon.ico
  repo-url: "{{< meta repository.url >}}"
  repo-actions: [edit, issue]
  sidebar:
    logo: assets/mlbd-logo-short.png
    logo-alt: "Machine Learning for Big Data logo"
    style: docked
    search: true
    contents:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: Group work
        href: group_work.qmd
      - text: Teaching notes
        href: teaching_notes.qmd
      - text: Resources
        href: resources.qmd

format:
  html:
    theme: cosmo
    toc: false
    css: assets/styles.css
    include-after-body: assets/repo-actions-bottom.html
    grid:
      sidebar-width: 280px
      body-width: 1000px
      margin-width: 280px
      gutter-width: 1.5rem


format-links: false

bibliography: references.bib
execute:
  freeze: auto
