---
title: "Feedback"
---

- Slides exercise to classify the analytical purpose was trivial. Include a bit more challenging (maybe code-based) examples.
- Clarify tidy data (using magnetic card organizing task on the blackboard?)
- Structure data preparation slides more clearly (do not combine tidy data structuring with other items on the slide)
- Tidy data vocabulary: explain *variable* and *observation*
- Include an example in tidy data for datasets that combine multiple observational units?
- Improve slide explanation of scales.


- Include `frankfurt_locations.csv` to be able to 

- Think how the second part of clustering should be presented (hierarchical; distance measures). It was covered (too) quickly in the last session.


Regression

2026-03-31: 80 mins for the lecture (slightly short, could be a bit more formal/challenging)

TODO

- prepare explanation of regression assumptions and diagnostics
- include transformations at the end (see https://ds100.org/course-notes/loss-transformations/#transformations-of-linear-models)
