---
title: "Notes: Orga"
format: html
---

::: {.callout-note title="Preparation"}
- Check room
- Print student list
- Prepare/bring tags to form groups
- Prepare a Teams session for students to share their work (update `instructor.online_meeting_url` in `course.yml`).
:::

| Time (min)  | Duration  | Topic                   |
|-------------|-----------|-------------------------|
| 00-20       | 20        | Orga                    |

## Myself

I do not know everything. I make mistakes. ...

- From running to studying
- ...

Mention surveys after each session (voluntary, but help me assess and prioritize)

Mention (without bullets on the slide)

- What I expect from students
- What students can expect from me

First round

- Lot of unknowns: how long session will take, how much you already know, what is challenging or easy
- I will learn as much as you will.
- I will ask for your feedback **very** regularly (at the end of each session)

## About you

Maybe:

- prior experience (e.g., python)?
- Ask students how they learn (PDF, ...) whether they use a knowledge management system (which one), ...

<!--
## Curriculum

## Analytics and why it matters

Takeaway - why analytics matters:
Analytics is not just about data.
It changes **how decisions are made, how organizations compete, and who wins.**
-->

{{< pagebreak >}}

## Course structure

- Highlight that the report submission will be approx. one month after the presentations.

## Not covered

- Engineering: "building the system"
- Statistical theory: "explaining the WHY"
- Mathematical models: "building more specialized models"
- Autonomous systems: "Implementing the decisions"

## Group work brief

Ask students to review the document (Canvas), discuss

- Dates/logistics suitable?
- Preferences for group formation?
- Anything to clarify? Questions?
- Take notes on topioc ideas and discuss them over the break. We will revisit them in the afternoon.

<!--
## Logistics

- Format of the session (exercises, preparation/reading)
- Summary presentations of practitioner materials?
- Consultation hour?

## Materials

- You always have the slides available (especially if you sit in the back, some slides may be hard to read)
-->

## Changelog

- Invested a lot of effort
- Hard to anticipate how long sessions will last: in some cases, we may complete the materials early (gives us some time to discuss the project work); if it takes too long, we can follow-up next time.

## Theses

- My students publish (very proud of them)
